const LICENSE_PUBLIC_KEY_ENV: &str = "CHROMVOID_LICENSE_PUBLIC_KEY_ED25519_2026_01";

fn main() {
    println!("cargo:rerun-if-env-changed={LICENSE_PUBLIC_KEY_ENV}");
    require_license_public_key_for_release();

    // Use ACL permissions for custom app commands (Tauri v2 capabilities).
    // Names here must match the command names used by `#[tauri::command]` (snake_case).
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "rpc_dispatch",
            "license_activation_code_activate",
            "license_account_cabinet_handoff",
            "license_status",
            "license_seat_status",
            "license_current_seat_deactivate",
            "module_access_snapshot",
            "module_access_resolve",
            "catalog_upload_chunk",
            "catalog_upload_native_files",
            "catalog_cancel_native_upload",
            "catalog_upload_android_shared_files",
            "catalog_cancel_android_shared_files",
            "passmanager_upload_chunk",
            "catalog_upload_path",
            "file_stat",
            "write_text_file",
            "catalog_download",
            "prepare_catalog_preview_file",
            "release_catalog_preview_file",
            "catalog_preview_image",
            "catalog_thumbnail_image",
            "catalog_image_metadata",
            "catalog_save_image_to_gallery",
            "catalog_share_files",
            "passmanager_download",
            "catalog_download_path",
            "catalog_open_external",
            "open_url_external",
            "catalog_secret_read",
            "catalog_secret_write_chunk",
            "passmanager_secret_read",
            "passmanager_secret_write_chunk",
            "get_current_mode",
            "init_local_storage",
            "master_setup",
            "master_rekey",
            "storage_set_root",
            "backup_local_create",
            "backup_local_cancel",
            "restore_local_from_folder",
            "restore_local_select_source",
            "restore_local_cancel",
            "erase_device",
            "gateway_get_config",
            "gateway_set_enabled",
            "gateway_set_access_duration",
            "gateway_list_paired",
            "gateway_revoke_extension",
            "gateway_start_pairing",
            "gateway_cancel_pairing",
            "gateway_set_session_duration",
            "gateway_get_capability_policy",
            "gateway_set_capability_policy",
            "gateway_issue_action_grant",
            "gateway_issue_site_grant",
            "gateway_list_active_grants",
            "gateway_revoke_all_grants",
            "get_session_settings",
            "set_session_settings",
            "volume_get_status",
            "volume_get_backends",
            "volume_mount",
            "volume_unmount",
            "touch_activity",
            "unlock_debug_log",
            "runtime_capabilities",
            "get_local_device_identity",
            "mobile_notify_background",
            "mobile_notify_foreground",
            "android_media_session_update",
            "android_media_session_stop",
            "android_audio_session_command",
            "android_video_start",
            "android_video_stop",
            "mobile_biometric_auth",
            "android_passkeys_list",
            "android_passkey_delete",
            "android_password_save_finish",
            "android_quick_lock_tile_status",
            "android_request_quick_lock_tile",
            "start_ios_host_mode",
            "stop_ios_host_mode",
            "ios_host_status",
            "publish_ios_presence",
            "handle_ios_wake",
            "mobile_acceptor_start",
            "mobile_acceptor_stop",
            "mobile_acceptor_status",
            "network_list_server_profiles",
            "network_get_bootstrap_profile",
            "network_connection_state",
            "network_list_paired_peers",
            "network_remove_paired_peer",
            "network_transport_metrics",
            "network_generate_room_id",
            "network_import_server_profile",
            "network_export_server_profile",
            "network_record_profile_endpoint_failure",
            "network_rollback_profile_endpoint",
            "network_pair_start",
            "network_pair_confirm",
            "network_pair_cancel",
            "sync_initial",
            "sync_delta_apply",
            "sync_reconnect",
            "sync_write",
            "mode_get",
            "mode_switch",
            "mode_status",
            "desktop_pair_ios",
            "desktop_connect_ios",
            "ssh_keygen",
            "ssh_agent_start",
            "ssh_agent_stop",
            "ssh_agent_status",
            "ssh_agent_sign_approval_resolve",
        ]),
    ))
    .expect("tauri-build failed");
}

fn require_license_public_key_for_release() {
    if std::env::var("PROFILE").ok().as_deref() != Some("release") {
        return;
    }

    let value = std::env::var(LICENSE_PUBLIC_KEY_ENV).unwrap_or_default();
    if value.trim().is_empty() {
        panic!("missing {LICENSE_PUBLIC_KEY_ENV}: release app builds must embed the license verification public key");
    }
}
