import type {GuidanceDefinition} from './guidance.types'

const actionKeys = {
  dismiss: 'guidance:actions:dismiss',
  later: 'guidance:actions:later',
  gotIt: 'guidance:actions:got-it',
  openHelp: 'guidance:actions:open-help',
} as const

const proBlockedBodyKeys = {
  unsupported: 'guidance:pro.blocked.unsupported:body',
  disabled_by_rollout: 'guidance:pro.blocked.disabled-by-rollout:body',
  entitlement_unavailable: 'guidance:pro.blocked.entitlement-unavailable:body',
  locked_pro: 'guidance:pro.blocked.locked-pro:body',
} as const

export const guidanceDefinitions: readonly GuidanceDefinition[] = [
  {
    id: 'welcome.local-vs-remote',
    surface: 'welcome',
    anchorId: 'welcome.vault-mode',
    trigger: 'first_run',
    presentation: 'popover',
    titleKey: 'guidance:welcome.local-vs-remote:title',
    bodyKey: 'guidance:welcome.local-vs-remote:body',
    secondaryActionKey: actionKeys.later,
    completion: {kind: 'product_state', key: 'vault.opened'},
    priority: 100,
    owner: 'welcome',
    version: 1,
  },
  {
    id: 'welcome.master-password',
    surface: 'welcome',
    anchorId: 'welcome.master-password',
    trigger: 'first_run',
    presentation: 'popover',
    titleKey: 'guidance:welcome.master-password:title',
    bodyKey: 'guidance:welcome.master-password:body',
    secondaryActionKey: actionKeys.later,
    completion: {kind: 'product_state', key: 'vault.created'},
    priority: 120,
    owner: 'welcome',
    version: 1,
  },
  {
    id: 'welcome.backup-restore',
    surface: 'welcome',
    anchorId: 'welcome.backup-tools',
    trigger: 'manual_help',
    presentation: 'inline_hint',
    titleKey: 'guidance:welcome.backup-restore:title',
    bodyKey: 'guidance:welcome.backup-restore:body',
    primaryActionKey: actionKeys.gotIt,
    completion: {kind: 'manual_ack'},
    priority: 50,
    owner: 'welcome',
    version: 1,
  },
  {
    id: 'welcome.erase-device-warning',
    surface: 'welcome',
    anchorId: 'welcome.erase-device',
    trigger: 'blocked_action',
    presentation: 'popover',
    titleKey: 'guidance:welcome.erase-device-warning:title',
    bodyKey: 'guidance:welcome.erase-device-warning:body',
    primaryActionKey: actionKeys.gotIt,
    completion: {kind: 'manual_ack'},
    priority: 80,
    owner: 'welcome',
    version: 1,
  },
  {
    id: 'files.empty-state',
    surface: 'files',
    anchorId: 'files.create-or-upload',
    trigger: 'empty_state',
    presentation: 'inline_hint',
    titleKey: 'guidance:files.empty-state:title',
    bodyKey: 'guidance:files.empty-state:body',
    completion: {kind: 'product_state', key: 'files.has_items'},
    priority: 10,
    owner: 'file-manager',
    version: 1,
  },
  {
    id: 'notes.empty-state',
    surface: 'notes',
    anchorId: 'notes.create-note',
    trigger: 'empty_state',
    presentation: 'inline_hint',
    titleKey: 'guidance:notes.empty-state:title',
    bodyKey: 'guidance:notes.empty-state:body',
    completion: {kind: 'product_state', key: 'notes.has_notes'},
    priority: 10,
    owner: 'notes',
    version: 1,
  },
  {
    id: 'passwords.empty-state',
    surface: 'passwords',
    anchorId: 'passwords.create-entry',
    trigger: 'empty_state',
    presentation: 'inline_hint',
    titleKey: 'guidance:passwords.empty-state:title',
    bodyKey: 'guidance:passwords.empty-state:body',
    completion: {kind: 'product_state', key: 'passwords.has_entries'},
    priority: 10,
    owner: 'passmanager',
    version: 1,
  },
  {
    id: 'passwords.import-migration',
    surface: 'passwords',
    anchorId: 'passwords.import',
    trigger: 'manual_help',
    presentation: 'popover',
    titleKey: 'guidance:passwords.import-migration:title',
    bodyKey: 'guidance:passwords.import-migration:body',
    primaryActionKey: actionKeys.gotIt,
    completion: {kind: 'manual_ack'},
    priority: 30,
    owner: 'passmanager',
    version: 1,
  },
  {
    id: 'passkeys.empty-state',
    surface: 'passkeys',
    anchorId: 'passkeys.manage',
    trigger: 'empty_state',
    presentation: 'inline_hint',
    titleKey: 'guidance:passkeys.empty-state:title',
    bodyKey: 'guidance:passkeys.empty-state:body',
    moduleAccessGate: {feature: 'credential-provider', statuses: ['enabled']},
    completion: {kind: 'product_state', key: 'passkeys.has_credentials'},
    priority: 25,
    owner: 'passkeys',
    version: 1,
  },
  {
    id: 'remote.setup-network',
    surface: 'remote',
    anchorId: 'remote.pair-device',
    trigger: 'feature_discovery',
    presentation: 'inline_hint',
    titleKey: 'guidance:remote.setup-network:title',
    bodyKey: 'guidance:remote.setup-network:body',
    capabilityGate: {supports_network_remote: true},
    completion: {kind: 'product_state', key: 'remote.has_paired_device'},
    priority: 40,
    owner: 'remote',
    version: 1,
  },
  {
    id: 'gateway.pair-extension',
    surface: 'gateway',
    anchorId: 'gateway.start-pairing',
    trigger: 'feature_discovery',
    presentation: 'popover',
    titleKey: 'guidance:gateway.pair-extension:title',
    bodyKey: 'guidance:gateway.pair-extension:body',
    moduleAccessGate: {feature: 'browser-extension', statuses: ['enabled']},
    completion: {kind: 'product_state', key: 'gateway.has_paired_extension'},
    priority: 80,
    owner: 'gateway',
    version: 1,
  },
  {
    id: 'pro.remote.blocked',
    surface: 'remote',
    anchorId: 'pro.access-state',
    trigger: 'blocked_action',
    presentation: 'popover',
    titleKey: 'guidance:pro.remote.blocked:title',
    bodyKey: 'guidance:pro.remote.blocked:body',
    bodyKeyByModuleAccessStatus: proBlockedBodyKeys,
    moduleAccessGate: {
      feature: 'remote',
      statuses: ['unsupported', 'disabled_by_rollout', 'entitlement_unavailable', 'locked_pro'],
    },
    primaryActionKey: actionKeys.openHelp,
    completion: {kind: 'manual_ack'},
    priority: 35,
    owner: 'module-access',
    version: 1,
  },
  {
    id: 'pro.gateway.blocked',
    surface: 'gateway',
    anchorId: 'pro.access-state',
    trigger: 'blocked_action',
    presentation: 'popover',
    titleKey: 'guidance:pro.gateway.blocked:title',
    bodyKey: 'guidance:pro.gateway.blocked:body',
    bodyKeyByModuleAccessStatus: proBlockedBodyKeys,
    moduleAccessGate: {
      feature: 'browser-extension',
      statuses: ['unsupported', 'disabled_by_rollout', 'entitlement_unavailable', 'locked_pro'],
    },
    primaryActionKey: actionKeys.openHelp,
    completion: {kind: 'manual_ack'},
    priority: 35,
    owner: 'module-access',
    version: 1,
  },
  {
    id: 'pro.remote-storage.blocked',
    surface: 'remote-storage',
    anchorId: 'pro.access-state',
    trigger: 'blocked_action',
    presentation: 'popover',
    titleKey: 'guidance:pro.remote-storage.blocked:title',
    bodyKey: 'guidance:pro.remote-storage.blocked:body',
    bodyKeyByModuleAccessStatus: proBlockedBodyKeys,
    moduleAccessGate: {
      feature: 'mounted-vault',
      statuses: ['unsupported', 'disabled_by_rollout', 'entitlement_unavailable', 'locked_pro'],
    },
    primaryActionKey: actionKeys.openHelp,
    completion: {kind: 'manual_ack'},
    priority: 35,
    owner: 'module-access',
    version: 1,
  },
  {
    id: 'remote-storage.mount-warning',
    surface: 'remote-storage',
    anchorId: 'remote-storage.mount',
    trigger: 'blocked_action',
    presentation: 'popover',
    titleKey: 'guidance:remote-storage.mount-warning:title',
    bodyKey: 'guidance:remote-storage.mount-warning:body',
    capabilityGate: {supports_volume: true},
    moduleAccessGate: {feature: 'mounted-vault', statuses: ['enabled']},
    completion: {kind: 'domain_event', event: 'volume_mount.started'},
    priority: 110,
    owner: 'remote-storage',
    version: 1,
  },
  {
    id: 'settings.ssh-agent',
    surface: 'settings',
    anchorId: 'settings.ssh-agent',
    trigger: 'feature_discovery',
    presentation: 'inline_hint',
    platforms: ['desktop', 'macos', 'linux', 'windows'],
    titleKey: 'guidance:settings.ssh-agent:title',
    bodyKey: 'guidance:settings.ssh-agent:body',
    moduleAccessGate: {feature: 'ssh-agent', statuses: ['enabled']},
    completion: {kind: 'product_state', key: 'ssh_agent.started'},
    priority: 15,
    owner: 'settings',
    version: 1,
  },
  {
    id: 'settings.mobile-autofill',
    surface: 'settings',
    anchorId: 'settings.mobile-autofill',
    trigger: 'feature_discovery',
    presentation: 'inline_hint',
    platforms: ['android'],
    titleKey: 'guidance:settings.mobile-autofill:title',
    bodyKey: 'guidance:settings.mobile-autofill:body',
    capabilityGate: {supports_autofill: true},
    moduleAccessGate: {feature: 'credential-provider', statuses: ['enabled']},
    completion: {kind: 'product_state', key: 'credential_provider.enabled'},
    priority: 90,
    owner: 'settings',
    version: 1,
  },
  {
    id: 'keyboard.shortcuts.files',
    surface: 'files',
    anchorId: 'shell.command-palette',
    trigger: 'manual_help',
    presentation: 'popover',
    platforms: ['desktop'],
    titleKey: 'guidance:keyboard.shortcuts.files:title',
    bodyKey: 'guidance:keyboard.shortcuts.files:body',
    primaryActionKey: actionKeys.gotIt,
    completion: {kind: 'manual_ack'},
    priority: 20,
    owner: 'shell',
    version: 1,
  },
  {
    id: 'keyboard.shortcuts.passwords',
    surface: 'passwords',
    anchorId: 'shell.command-palette',
    trigger: 'manual_help',
    presentation: 'popover',
    platforms: ['desktop'],
    titleKey: 'guidance:keyboard.shortcuts.passwords:title',
    bodyKey: 'guidance:keyboard.shortcuts.passwords:body',
    primaryActionKey: actionKeys.gotIt,
    completion: {kind: 'manual_ack'},
    priority: 20,
    owner: 'shell',
    version: 1,
  },
  {
    id: 'keyboard.shortcuts.notes',
    surface: 'notes',
    anchorId: 'shell.command-palette',
    trigger: 'manual_help',
    presentation: 'popover',
    platforms: ['desktop'],
    titleKey: 'guidance:keyboard.shortcuts.notes:title',
    bodyKey: 'guidance:keyboard.shortcuts.notes:body',
    primaryActionKey: actionKeys.gotIt,
    completion: {kind: 'manual_ack'},
    priority: 20,
    owner: 'shell',
    version: 1,
  },
]
